version: '3'

services:
  fastapi_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_DB: supermarket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Manaus
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  fastapi_app:
    build: .
    depends_on:
      - fastapi_db
    environment:
      DB_HOST: db
      DATABASE_URL: postgresql+psycopg://postgres:postgres@fastapi_db:5432/supermarket_db
    ports:
      - "8080:8081"

volumes:
  pg_data: